Fix tests for Python3.6 by removing asyncio-mode as it's not supported. (#332)
Summary:
**What:**

CI tests are currently [failing](https://github.com/facebook/TestSlide/actions/runs/2158772378) for Python3.6 with the error:

```
ERROR: usage: __main__.py [options] [file_or_dir] [file_or_dir] [...]
__main__.py: error: unrecognized arguments: --asyncio-mode=auto
  inifile: None
```

**Why:**

CI/unit tests are failing for Python3.6.
I believe this failure was introduced with [this](https://github.com/facebook/TestSlide/pull/328) change and [pytest-asyncio](https://github.com/pytest-dev/pytest-asyncio) seems to be 3.7+ compatible.

**How:**

Do not run pytest with `--asyncio-mode=auto` for Python3.6

**Risks:**

None identified.

**Checklist**:

- [ ] Added tests, if you've added code that should be tested (N/A)
- [ ] Updated the documentation, if you've changed APIs( N/A)
- [X] Ensured the test suite passes
- [X] Made sure your code lints
- [X] Completed the Contributor License Agreement ("CLA")

Pull Request resolved: https://github.com/facebook/TestSlide/pull/332

Reviewed By: cjcon90

Differential Revision: D35643124

Pulled By: deathowl

fbshipit-source-id: 62ed607d51abacce45e37654181907c6a8310501